version: "3.3"

services:
  database:
    container_name: django-shop
    image: postgres
    restart: unless-stopped
    volumes:
    - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=dshop
      - POSTGRES_USER=dshop
    ports:
      - 5432:5432
  celery_broker:
    container_name: djangoshop_celery_broker
    image: rabbitmq:3.8.9
    restart: unless-stopped
    command: rabbitmq-server
    ports:
      - 5672:5672